// <auto-generated />
namespace TrendAudioFromSpotify.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddedIsPublicpropertytoPlaylistDto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedIsPublicpropertytoPlaylistDto));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031158400_Added IsPublic property to PlaylistDto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
